apiVersion: v1
kind: ReplicationController
metadata:
   name: myweb1-rc
spec:
  replicas: 3
  selector:
      env: production
  template:
    metadata:
       name: myweb1-pod
       labels:
          env: production
    spec:
      containers:
      -  name: myweb1-con
         image: httpd